import Client from "../stream/Client";
import {
    config,
    ChatObject,
    StatusObject,
    StreamEvents,
    ConnectedUsersObject, UserDataObject, SendChatObject, verifyString
} from "../lib/utility";
import IStreamObserver from "../stream/IStreamObserver";

/**
 * Class containing base logic every chat room should include
 * @author Connell Reffo
 */
export default abstract class AbstractChatRoom implements IStreamObserver {

    /**
     * Set of unique clients connected to this chat room
     */
    protected clients: Set<Client>;

    /**
     * Name of this chat room
     */
    protected name: string;

    /**
     * Unique ID of this chat room <br />
     * Generated by the factory
     */
    protected id: number;

    /**
     * Base constructor
     * @param name The name of this room
     * @param id The ID of this room
     */
    public constructor(name: string, id: number) {
        this.name = name;
        this.id = id;
        this.clients = new Set<Client>;
    }

    /**
     * @inheritDoc
     */
    public abstract onClientJoined(client: Client): void;

    /**
     * @inheritDoc
     */
    public abstract onClientConnected(client: Client): void;

    /**
     * @inheritDoc
     */
    public onClientDisconnected(client: Client): void {
        this.removeClientAndBroadcast(client);
    }

    /**
     * @inheritDoc
     */
    public onClientMessage(client: Client, message: ChatObject): void {
        const status: StatusObject = this.verifyClientMessage(message);
        const data: SendChatObject = {
            username: client.getName(),
            roomId: message.roomId,
            message: message.text
        };

        if (status.success) {
            this.broadcast(StreamEvents.SERVER_CHAT_RESPONSE, data);
        }
        else {
            client.emit(StreamEvents.SERVER_SEND_STATUS, status);
        }
    }

    /**
     * Adds a client as a member to this chat room and broadcasts that a client was added to the rest of the room
     * @param client The client to add
     */
    public addClientAndBroadcast(client: Client): void {
        this.clients.add(client);
        this.broadcast(StreamEvents.SERVER_UPDATE_CONNECTIONS, this.encodeConnections());
    }

    /**
     * Removes a client as a member from this chat room and broadcasts the new connections encoding
     * @param client The client to be removed
     */
    public removeClientAndBroadcast(client: Client): void {
        this.clients.delete(client);
        this.broadcast(StreamEvents.SERVER_UPDATE_CONNECTIONS, this.encodeConnections());
    }

    /**
     * Verifies that a message received by this room is valid to be broadcast <br />
     * Essentially a filter
     * @param message The message to be verified
     */
    public verifyClientMessage(message: ChatObject): StatusObject {
        return {
            success: (this.id == message.roomId && verifyString(message.text, config.MIN_MESSAGE_LENGTH, config.MAX_MESSAGE_LENGTH))
        };
    }

    /**
     * Encodes the connections of this room as an object
     */
    public encodeConnections(): ConnectedUsersObject {
        return {
            roomId: this.id,
            connections: Array.from(this.clients).map((c: Client): UserDataObject => ({username: c.getName()}))
        };
    }

    /**
     * Emits a message to every client connected to this room
     * @param event The event to emit
     * @param data The data to be sent
     */
    public broadcast(event: StreamEvents|string, data: {}): void {
        this.clients.forEach((client: Client): void => {
            client.emit(event, data);
        });
    }

    /**
     * Gets the name of this chat room
     */
    public getName(): string {
        return this.name;
    }

    /**
     * Gets the ID of this chat room
     */
    public getID(): number {
        return this.id;
    }

    /**
     * Checks if this chat room has a specified client
     * @param client Is the client to check membership for
     */
    public hasClient(client: Client): boolean {
        return this.clients.has(client);
    }
}