name: Chatter Client CI (Vitest)

on: [push]

jobs:
  vitest:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: ${{github.workspace}}/chatter-client/package-lock.json
      - name: Build And Test With Vitest
        run: |
          npm install
          npm run build --if-present
          npm run test
        working-directory: "chatter-client"